Add jest test setup and fix tsc rules fix method
cloudflightio/cloudflight-eslint-plugin pull request #9
Opened 2022-09-15 10:12 UTC by sniederhumer

- Add jest setup and configuration to allow custom rule tests
- Add example test for tsc-allow-unreachable-code
- Generate missing property on fix when compiler options are empty
- Bump patch version to 0.3.1 for fix

2022-09-15 11:13 UTC, strawberry-choco requested changes
You also need to adjust https://github.com/cloudflightio/cloudflight-eslint-plugin/blob/main/.github/workflows/build.yml to make the tests run on the ci.

Other than that this PR is awesome. :)

2022-09-15 11:13 UTC, strawberry-choco commented on jest.config.base.js
> +module.exports = {
Shouldn't jest configs also work as typescript files? https://jestjs.io/docs/configuration

2022-09-15 12:09 UTC, cgrabmann approved these changes

2022-09-15 14:06 UTC, sniederhumer commented
> You also need to adjust https://github.com/cloudflightio/cloudflight-eslint-plugin/blob/main/.github/workflows/build.yml to make the tests run on the ci.
> 
> Other than that this PR is awesome. :)

Pushed another PR with fixes and updated the build.yml as well!

2022-09-16 06:29 UTC, strawberry-choco approved these changes

2022-09-16 06:29 UTC, merged